---
- hosts: all
  gather_facts: true
  tasks:
    - name: Update all packages to their latest version
      apt:
          name: "*"
          state: latest
    - name: Install npm
      apt:
          name: npm
          state: present
    - name: Install apache httpd  (state=present is optional)
      apt:
          name: apache2
          state: absent
    